#!/usr/bin/env python3
"""Corpus-observed parameter defaults (D30).

When Loxone Config places a block it writes a `Def=` for (almost) every
port — at the GUI default. Across a corpus of real configs the default is
therefore the overwhelmingly modal value: this script counts the `Def=`
distribution per (block type, port key) and calls a value the *observed
default* when it holds at least SHARE of the occurrences and at least
MIN_OBS occurrences exist.

Two outputs:

    tools/extract-defaults.py <corpus-dir>

writes the full evidence (every type, every port, modal value, share,
counts) to docs/data/param-defaults.json, and regenerates
src/observed_defaults.rs with the accepted entries restricted to the
builtin (managed) types from src/connectors.rs — the only types whose
parameters the decompiler ever lifts. The Rust file is generated: edit
this script or the thresholds, never the table.

The table is view-only knowledge: the Full decompile view elides a lifted
parameter whose value equals the observed default (`--all-params` shows
everything); the adoptable ManagedOnly view never elides. A wrong entry
can therefore hide a real value from a *reading* human but can never
change what compiles — which is why corpus statistics clear the bar here
while the connector DB proper still demands live verification.
"""

import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

try:  # corpus files are third-party downloads — parse them defensively
    from defusedxml import ElementTree as ET
except ImportError:
    import xml.etree.ElementTree as ET

SHARE = 0.90  # modal value must hold at least this share of occurrences
MIN_OBS = 10  # and be observed at least this often

REPO = Path(__file__).resolve().parent.parent


def builtin_types() -> list[str]:
    src = (REPO / "src" / "connectors.rs").read_text(encoding="utf-8")
    start = src.index("pub const BUILTIN_TYPES")
    end = src.index("];", start)
    return re.findall(r'"([A-Za-z0-9_]+)"', src[start:end])


def scan(corpus: Path):
    # (type, port) -> Counter of Def values; and how often Def was absent.
    defs: dict[tuple[str, str], Counter] = defaultdict(Counter)
    absent: Counter = Counter()
    files = sorted(corpus.glob("*.Loxone"))
    if not files:
        sys.exit(f"no .Loxone files in {corpus}")
    parsed = 0
    for path in files:
        try:
            root = ET.parse(path).getroot()
        except ET.ParseError as e:
            # This tool is statistics, not the product parser — skipping a
            # file ET cannot digest only shrinks the sample.
            print(f"skip {path.name}: {e}", file=sys.stderr)
            continue
        parsed += 1
        for c in root.iter("C"):
            btype = c.get("Type")
            if not btype:
                continue
            for co in c.findall("Co"):
                key = co.get("K")
                if not key:
                    continue
                d = co.get("Def")
                if d is None:
                    absent[(btype, key)] += 1
                else:
                    defs[(btype, key)][d] += 1
    return defs, absent, parsed


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    corpus = Path(sys.argv[1])
    defs, absent, nfiles = scan(corpus)

    evidence: dict[str, dict[str, dict]] = defaultdict(dict)
    accepted: list[tuple[str, str, str]] = []
    builtins = set(builtin_types())
    for (btype, key), counter in sorted(defs.items()):
        total = sum(counter.values())
        value, top = counter.most_common(1)[0]
        share = top / total
        entry = {
            "value": value,
            "share": round(share, 4),
            "with_def": total,
            "top": top,
            "absent": absent.get((btype, key), 0),
            "accepted": share >= SHARE and total >= MIN_OBS,
        }
        evidence[btype][key] = entry
        if entry["accepted"] and btype in builtins:
            accepted.append((btype, key, value))

    out = REPO / "docs" / "data" / "param-defaults.json"
    out.write_text(
        json.dumps(
            {
                "_meta": {
                    "corpus_files": nfiles,
                    "share_threshold": SHARE,
                    "min_observations": MIN_OBS,
                    "tool": "tools/extract-defaults.py",
                },
                **{t: evidence[t] for t in sorted(evidence)},
            },
            indent=1,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )

    rs = REPO / "src" / "observed_defaults.rs"
    lines = [
        "//! Corpus-observed parameter defaults (D30). GENERATED by",
        "//! `tools/extract-defaults.py` — do not edit; regenerate with:",
        "//!",
        "//! ```sh",
        "//! tools/extract-defaults.py corpus/web",
        "//! ```",
        "//!",
        "//! An entry means: across the local corpus"
        f" ({nfiles} real configs),",
        f"//! at least {SHARE:.0%} of this port's `Def=` occurrences"
        f" (min {MIN_OBS})",
        "//! carried this value — the value Loxone Config writes at block",
        "//! placement, i.e. the GUI default. Full evidence, including the",
        "//! rejected long tail, lives in docs/data/param-defaults.json.",
        "//!",
        "//! View-only knowledge: the `Full` decompile view elides a lifted",
        "//! parameter equal to the observed default (D30); the adoptable",
        "//! `ManagedOnly` view never does. A wrong entry can hide a value",
        "//! from a reading human but can never change what compiles.",
        "",
        "/// The corpus-observed default `Def=` for a builtin block's port,",
        "/// as the exact attribute string.",
        "pub fn observed_default(block_type: &str, port: &str)"
        " -> Option<&'static str> {",
        "    Some(match (block_type, port) {",
    ]
    for btype, key, value in accepted:
        v = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'        ("{btype}", "{key}") => "{v}",')
    lines += [
        "        _ => return None,",
        "    })",
        "}",
        "",
    ]
    rs.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"{out.relative_to(REPO)}: {sum(len(v) for v in evidence.values())}"
        f" (type, port) pairs from {nfiles} configs;"
        f" {rs.relative_to(REPO)}: {len(accepted)} accepted builtin entries"
    )


if __name__ == "__main__":
    main()
