//! Corpus-observed parameter defaults (D30). GENERATED by
//! `tools/extract-defaults.py` — do not edit; regenerate with:
//!
//! ```sh
//! tools/extract-defaults.py corpus/web
//! ```
//!
//! An entry means: across the local corpus (111 real configs),
//! at least 90% of this port's `Def=` occurrences (min 10)
//! carried this value — the value Loxone Config writes at block
//! placement, i.e. the GUI default. Full evidence, including the
//! rejected long tail, lives in docs/data/param-defaults.json.
//!
//! View-only knowledge: the `Full` decompile view elides a lifted
//! parameter equal to the observed default (D30); the adoptable
//! `ManagedOnly` view never does. A wrong entry can hide a value
//! from a reading human but can never change what compiles.

/// The corpus-observed default `Def=` for a builtin block's port,
/// as the exact attribute string.
pub fn observed_default(block_type: &str, port: &str) -> Option<&'static str> {
    Some(match (block_type, port) {
        ("AutoJalousie", "AutoShadeEnd") => "1",
        ("AutoJalousie", "Back") => "0.8",
        ("AutoJalousie", "DblClk") => "0.3",
        ("AutoJalousie", "Dir") => "180",
        ("AutoJalousie", "DirTol") => "85",
        ("AutoJalousie", "DirTol2") => "85",
        ("AutoJalousie", "MinMove") => "0.4",
        ("AutoJalousie", "MinPulse") => "3",
        ("AutoJalousie", "SRoff") => "30",
        ("AutoJalousie", "SSoff") => "-30",
        ("AutoJalousie", "Space") => "60",
        ("AutoJalousie", "TimeBlock") => "0.5",
        ("AutoJalousie", "Width") => "70",
        ("LightController2", "AlarmBrightness") => "50",
        ("LightController2", "AlarmClockPeriod") => "3",
        ("LightController2", "AlarmPeriod") => "4",
        ("LightController2", "BrightnessLimit") => "30",
        ("LightController2", "DayMaxTemp") => "6500",
        ("LightController2", "DayMinTemp") => "2700",
        ("LightController2", "FadingTime") => "1",
        ("LightController2", "Max") => "100",
        ("LightController2", "MaxP") => "0.35",
        ("LightController2", "MoveTimeout") => "3600",
        ("LightController2", "SceneMixTime") => "1",
        ("LightController2", "Step") => "2",
        ("LightController2", "Steptime") => "0.2",
        _ => return None,
    })
}
